// Pages Actions
const PagesActionTypes = {
  SET_START_PAGE_ANIMATION: "PAGES/SET_START_PAGE_ANIMATION",
  SET_SCORES_PAGE_ANIMATION: "PAGES/SET_SCORES_PAGE_ANIMATION",
};

export default PagesActionTypes;
