const DeckActionTypes = {
  SET_INITIAL_DECK: "SET_INITIAL_DECK",
  FLIP_DECK_PILE: "FLIP_DECK_PILE",
  SET_REFS: "SET_REFS",
  SET_TRANSLATION: "SET_TRANSLATION",
  RESET_DECK: "RESET_DECK"
};

export default DeckActionTypes;
