// Deck Actions
const DeckActionTypes = {
  SET_INITIAL_DECK: "SET_INITIAL_DECK",
  SET_REFS: "SET_REFS",
  SET_TRANSLATION: "SET_TRANSLATION",
  FLIP_DECK_PILE: "FLIP_DECK_PILE",
  RESET_DECK: "RESET_DECK",
  DRAG_FLIPPED_CARD: "DRAG_FLIPPED_CARD",
  RESTORE_FLIPPED_CARD: "RESTORE_FLIPPED_CARD",
  RESET_CARD_DRAGGING: "RESET_CARD_DRAGGING"
};

export default DeckActionTypes;
