// Goal Actions
const GoalActionTypes = {
  SWAP_GOALS: "GOALS/SWAP_GOALS",
  UNSWAP_GOALS: "GOALS/UNSWAP_GOALS",
  DRAG_GOAL_CARDS: "GOALS/DRAG_GOAL_CARDS",
  ADD_DRAGGING_CARDS_TO_GOAL: "GOALS/ADD_DRAGGING_CARDS_TO_GOAL",
  RESET_GOAL_CARD_DRAGGING: "GOALS/RESET_GOAL_CARD_DRAGGING",
  ADD_CARD_TO_GOAL: "GOALS/ADD_CARD_TO_GOAL",
  REMOVE_CARD_FROM_GOAL: "GOALS/REMOVE_CARD_FROM_GOAL"
};

export default GoalActionTypes;
