// Goal Actions
const GoalActionTypes = {
  DRAG_GOAL_CARDS: "DRAG_GOAL_CARDS",
  ADD_DRAGGING_CARDS_TO_GOAL: "ADD_DRAGGING_CARDS_TO_GOAL",
  REMOVE_GOAL_CARD: "REMOVE_GOAL_CARD",
  RESET_GOAL_CARD_DRAGGING: "RESET_GOAL_CARD_DRAGGING",
  SWAP_GOALS: "SWAP_GOALS",
  UNSWAP_GOALS: "UNSWAP_GOALS",
  SEND_UNDO_CARDS_TO_GOAL: "SEND_UNDO_CARDS_TO_GOAL",
  SET_UNDO_GOAL_CARDS: "SET_UNDO_GOAL_CARDS"
};

export default GoalActionTypes;
