// Goal Actions
const GoalActionTypes = {
  SWAP_GOALS: "GOALS/SWAP_GOALS",
  UNSWAP_GOALS: "GOALS/UNSWAP_GOALS",
  DRAG_GOAL_CARDS: "GOALS/DRAG_GOAL_CARDS",
  ADD_DRAGGING_CARDS_TO_GOAL: "GOALS/ADD_DRAGGING_CARDS_TO_GOAL",
  RESET_GOAL_CARD_DRAGGING: "GOALS/RESET_GOAL_CARD_DRAGGING",
  ADD_CARD_TO_GOAL: "GOALS/ADD_CARD_TO_GOAL",
  REMOVE_CARD_FROM_GOAL: "GOALS/REMOVE_CARD_FROM_GOAL",
  HANDLE_DOUBLE_CLICK: "GOALS/HANDLE_DOUBLE_CLICK",
  CHECK_GOAL_SWAP_DOUBLE_CLICK_VALID:
    "GOALS/CHECK_GOAL_SWAP_DOUBLE_CLICK_VALID",
  CHECK_DOUBLE_CLICK_VALID: "GOALS/CHECK_DOUBLE_CLICK_VALID"
};

export default GoalActionTypes;
