// HighScores Actions
const HighScoresActionTypes = {
  SET_ONLINE_HIGHSCORES: "HIGHSCORES/SET_ONLINE_HIGHSCORES",
  SET_OFFLINE_HIGHSCORES: "HIGHSCORES/SET_OFFLINE_HIGHSCORES",
  ADD_HIGHSCORE: "HIGHSCORES/ADD_HIGHSCORE"
};

export default HighScoresActionTypes;
