// Columns Actions
const ColumnsActionTypes = {
  SET_INITIAL_COLUMNS: "SET_INITIAL_COLUMNS",
  SWAP_COLUMNS: "SWAP_COLUMNS",
  UNDO_SWAP_COLUMNS: "UNDO_SWAP_COLUMNS",
  DRAG_COLUMN_CARDS: "DRAG_COLUMN_CARDS",
  ADD_DRAGGING_CARDS_TO_COLUMN: "ADD_DRAGGING_CARDS_TO_COLUMN",
  RESET_COLUMN_CARD_DRAGGING: "RESET_COLUMN_CARD_DRAGGING",
  REMOVE_CARD: "REMOVE_CARD",
  UNDO_MOVE_TO_COLUMN: "UNDO_MOVE_TO_COLUMN"
};

export default ColumnsActionTypes;
