// Columns Actions
const ColumnsActionTypes = {
  SET_INITIAL_COLUMNS: "SET_INITIAL_COLUMNS",
  SWAP_COLUMNS: "SWAP_COLUMNS",
  UNDO_SWAP_COLUMNS: "UNDO_SWAP_COLUMNS",
  DRAG_COLUMN_CARDS: "DRAG_COLUMN_CARDS",
  ADD_DRAGGING_CARDS_TO_COLUMN: "ADD_DRAGGING_CARDS_TO_COLUMN",
  RESET_COLUMN_CARD_DRAGGING: "RESET_COLUMN_CARD_DRAGGING",
  REMOVE_CARD: "REMOVE_CARD",
  SEND_UNDO_CARDS_TO_COLUMN: "SEND_UNDO_CARDS_TO_COLUMN",
  SET_UNDO_COLUMN_CARDS: "SET_UNDO_COLUMN_CARDS"
};

export default ColumnsActionTypes;
