const ColumnsActionTypes = {
  SET_INITIAL_COLUMNS: "SET_INITIAL_COLUMNS",
  SWAP_COLUMNS: "SWAP_COLUMNS",
  SET_CARD_DRAGGING: "SET_CARD_DRAGGING",
  REMOVE_CARD_DRAGGING: "REMOVE_CARD_DRAGGING"
};

export default ColumnsActionTypes;
