// User Actions
const UserActionTypes = {
  SAVE_USER: "USER/SAVE_USER",
  GET_LOCAL_STORAGE: "USER/GET_LOCAL_STORAGE",
  CHANGE_USERNAME: "USER/CHANGE_USERNAME",
  ADD_GAME: "USER/ADD_GAME",
  GAME_OVER: "USER/GAME_OVER",
  SAVE_GAME: "USER/SAVE_GAME",
  CLEAR_SAVED_GAME: "USER/CLEAR_SAVED_GAME"
};

export default UserActionTypes;
